name: Windup PR builder for JDK11

on:
  pull_request:
    branches:
      - master
    types:
      - edited

jobs:
  windup-build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          repository: jmle/windup
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          java-package: jdk
          cache: 'maven'
      - name: Build
        run: |
          git fetch
          git checkout WINDUP-3235
          mvn clean install -DskipTests

  windup-rulesets-build:
    runs-on: ubuntu-18.04
    needs: [windup-build]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          java-package: jdk
          cache: 'maven'
      - name: Build
        run: mvn clean install


